version: '3.8'

services:
  frontend:
    build: .
    image: ${DOCKER_USERNAME}/portfolio-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./fast_api_backend
    image: ${DOCKER_USERNAME}/portfolio-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    restart: always