name: Deploy FastAPI Backend

on:
  push:
    branches: [ OS ]
    paths:
      - '.github/workflows/backend.yml'
      - 'fast_api_backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./fast_api_backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest

      - name: Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Deploy backend container
            cd /var/www/html/portfolio
            docker stop portfolio-backend || true
            docker rm portfolio-backend || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest
            docker run -d \
              --name portfolio-backend \
              -p 8000:8000 \
              --env-file .env.production \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest

            # Configure Apache proxy
            sudo a2enmod proxy
            sudo a2enmod proxy_http
            
            # Create proxy configuration
            sudo tee /etc/apache2/sites-available/api-proxy.conf << EOF
            <VirtualHost *:80>
                ServerName api.yourdomain.com
                ProxyPreserveHost On
                ProxyPass /api/ http://localhost:8000/
                ProxyPassReverse /api/ http://localhost:8000/
            </VirtualHost>
            EOF

            # Enable site and restart Apache
            sudo a2ensite api-proxy.conf
            sudo systemctl restart apache2