name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'fast_api_backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./fast_api_backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Setup Apache config
            sudo tee /etc/apache2/sites-available/portfolio.conf << EOF
            <VirtualHost *:80>
                ServerAdmin webmaster@localhost
                DocumentRoot /var/www/html

                ProxyPreserveHost On
                ProxyPass /api http://localhost:8000
                ProxyPassReverse /api http://localhost:8000

                ErrorLog \${APACHE_LOG_DIR}/error.log
                CustomLog \${APACHE_LOG_DIR}/access.log combined
            </VirtualHost>
            EOF

            # Enable Apache modules and site
            sudo a2enmod proxy
            sudo a2enmod proxy_http
            sudo a2ensite portfolio.conf
            
            # Restart container
            cd /var/www/html/portfolio
            docker stop portfolio-backend || true
            docker rm portfolio-backend || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest
            docker run -d \
              --name portfolio-backend \
              -p 8000:8000 \
              --env-file .env.production \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest

            # Restart Apache
            sudo systemctl restart apache2