name: Deploy FastAPI Backend

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/backend.yml'
      - 'fast_api_backend/**'
      - 'docker-compose.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./fast_api_backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest

      - name: Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html/portfolio
            docker stop portfolio-backend || true
            docker rm portfolio-backend || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest
            docker run -d \
              --name portfolio-backend \
              -p 8000:8000 \
              --env-file .env.production \
              --restart always \
              ${{ secrets.DOCKER_USERNAME }}/portfolio-backend:latest