name: FastAPI Backend CI/CD

on:
  push:
    branches: [ O ]
  pull_request:
    branches: [ S ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Step 4: Copy FastAPI files to the server using SCP
      - name: Copy FastAPI files using SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "fast_api_backend/*"
          target: "/var/www/html/portfolio"
          rm: false
          strip_components: 1

      # Step 5: Make deploy script executable and run it
      - name: Run deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            chmod +x /var/www/html/portfolio/deploy.sh
            /var/www/html/portfolio/deploy.sh
